// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GetPhoneNumberClient is the client API for GetPhoneNumber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetPhoneNumberClient interface {
	GetNum(ctx context.Context, in *Pid, opts ...grpc.CallOption) (*Person, error)
}

type getPhoneNumberClient struct {
	cc grpc.ClientConnInterface
}

func NewGetPhoneNumberClient(cc grpc.ClientConnInterface) GetPhoneNumberClient {
	return &getPhoneNumberClient{cc}
}

func (c *getPhoneNumberClient) GetNum(ctx context.Context, in *Pid, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/messages.GetPhoneNumber/GetNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPhoneNumberServer is the server API for GetPhoneNumber service.
// All implementations must embed UnimplementedGetPhoneNumberServer
// for forward compatibility
type GetPhoneNumberServer interface {
	GetNum(context.Context, *Pid) (*Person, error)
	mustEmbedUnimplementedGetPhoneNumberServer()
}

// UnimplementedGetPhoneNumberServer must be embedded to have forward compatible implementations.
type UnimplementedGetPhoneNumberServer struct {
}

func (UnimplementedGetPhoneNumberServer) GetNum(context.Context, *Pid) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNum not implemented")
}
func (UnimplementedGetPhoneNumberServer) mustEmbedUnimplementedGetPhoneNumberServer() {}

// UnsafeGetPhoneNumberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetPhoneNumberServer will
// result in compilation errors.
type UnsafeGetPhoneNumberServer interface {
	mustEmbedUnimplementedGetPhoneNumberServer()
}

func RegisterGetPhoneNumberServer(s grpc.ServiceRegistrar, srv GetPhoneNumberServer) {
	s.RegisterService(&_GetPhoneNumber_serviceDesc, srv)
}

func _GetPhoneNumber_GetNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetPhoneNumberServer).GetNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.GetPhoneNumber/GetNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetPhoneNumberServer).GetNum(ctx, req.(*Pid))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetPhoneNumber_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.GetPhoneNumber",
	HandlerType: (*GetPhoneNumberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNum",
			Handler:    _GetPhoneNumber_GetNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
